name: Static analysis

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions:
  contents: read

jobs:
  psalm:
    name: Psalm
    runs-on: Ubuntu-20.04

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo
          ini-values: "memory_limit=-1"
          coverage: none

      - name: Install dependencies
        run: |
          ls -al
          composer install
          

      - name: Psalm
        run: |
          ./vendor/bin/psalm.phar --no-progress || ./vendor/bin/psalm.phar --output-format=github --no-progress
